services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on localhost
    volumes:
      - mongo_data:/data/db  # Persist data locally

  app:
    build:
      context: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017  # Connect to MongoDB service
    volumes:
      - ./app:/usr/src/app
    command: python main.py

volumes:
  mongo_data:
